version: 2

sources:
  - name: raw_data
    description: "raw_data"
    database: dtc-de-course-485410 
    schema: nytaxi
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
